package stickers

import (
	"math/rand"
	"time"
)

// StickerCategories maps human emotion categories to verified Telegram sticker file_ids
var StickerCategories = map[string][]string{
	"agreement": {
		"CAACAgUAAxUAAWleQX_Yo6YeVKhybdQnHawUvD8bAAL_FwAClRIIVH5ZppESLlMKHgQ",
		"CAACAgUAAxUAAWleQYD9qcaf9wABWFCseb0WUIELsAACVxMAAqG1uFTwh9apWXkXYh4E",
		"CAACAgUAAxUAAWleQYBdGk9KGRLUdi71f8iJ146xAAJBFAACiWLBVJcLk2OV1wyGHgQ",
		"CAACAgUAAxUAAWleQYBdGk9KGRLUdi71f8iJ146xAAJBFAACiWLBVJcLk2OV1wyGHgQ",
		"CAACAgUAAxUAAWleQYDduc7SZlrgj8PLJyfggsYrAAIyEwACq3HBVdQPnLReflINHgQ",
		"CAACAgUAAxkBAAIHoGq31N4E3_y7jswiBnFY785P6P3gAAL1HQACyS_hVUnH_ZZ_S2mNHgQ",
	},
	"angry": {
		"CAACAgUAAxUAAWleQX7cZpmIV2M6QkxSSeiyAAH2wQACSA4AAicmsVX85pCoeP3wdx4E",
		"CAACAgUAAxUAAWleQX_WWO1nBGB-cCPrlJhQxEheAAIjCQACjisgVhzfktSgAAGmOB4E",
		"CAACAgUAAxUAAWleQX-3AlD76a9c73RHQlt8KdhgAAKtEAACOpCIVy33JOex74nJHgQ",
		"CAACAgUAAxUAAWleQX91tQQbid6L10b1GPj8i1LpAAKGFQADWIlWu0Y7sW8Gu-keBA",
		"CAACAgUAAxUAAWleQYDd-cK5hyMvHYo9erf4qEeMAAIIFQACOfkIV-_3KAzOwONRHgQ",
		"CAACAgUAAxUAAWleQYADVpxTvY5eHrJ6RSNlBFzjAAIBFgAClrvBVCuKtM2kllLPHgQ",
		"CAACAgUAAxUAAWleQYBQTWDLEnl2NIRUsuyUfqYbAAK-EwAC4pK5VJxyrXT6TUOWHgQ",
		"CAACAgUAAxUAAWleQYBQTWDLEnl2NIRUsuyUfqYbAAK-EwAC4pK5VJxyrXT6TUOWHgQ",
		"CAACAgUAAxUAAWleQYBQTWDLEnl2NIRUsuyUfqYbAAK-EwAC4pK5VJxyrXT6TUOWHgQ",
		"CAACAgUAAxUAAWleQYBQTWDLEnl2NIRUsuyUfqYbAAK-EwAC4pK5VJxyrXT6TUOWHgQ",
		"CAACAgUAAxUAAWleQYBQTWDLEnl2NIRUsuyUfqYbAAK-EwAC4pK5VJxyrXT6TUOWHgQ",
		"CAACAgUAAxUAAWleQYBQTWDLEnl2NIRUsuyUfqYbAAK-EwAC4pK5VJxyrXT6TUOWHgQ",
		"CAACAgUAAxUAAWleQYCyxqnrkkhx52jOcsX5mklFAAL9EwACCk0QVWsu9YjMw5UQHgQ",
		"CAACAgUAAxUAAWleQYBb3ot8Jppyu0UjtKzSHMthAAIMHAACcP8JVSJPHpCyH6UkHgQ",
	},
	"blushing": {
		"CAACAgUAAxUAAWleQX521n7cRUREFy9pcQazeZVOAALGCwACnHSpVWvO__Hn0F4AAR4E",
		"CAACAgUAAxUAAWleQX8JzqRYLyDkXtX6_fV4nFEoAALMEgACF6aIV1ZD22yXirbGHgQ",
		"CAACAgUAAxUAAWleQX8mTlydVj1MNq9TNTMuWS2JAALfDwACpnW5V7jQsb164IzgHgQ",
		"CAACAgUAAxUAAWleQX_U1V-U27jfKkIphcpRg9v3AAJ4DwACXaX5Vy3-9oV4KOk3HgQ",
		"CAACAgUAAxUAAWleQX-udTy-2rXe0M8IIkwJzbWqAAIWFwACQoh4VAsKDONVBYrQHgQ",
		"CAACAgUAAxUAAWleQYDgK5psKt7IZcm0HWPagCfGAALDDwACGVYZVw-QCpxtqeqsHgQ",
		"CAACAgUAAxUAAWleQYD0IjYMlTqZ2mpR1-mjvcQoAAJeDwACW-dJVTonXkmbwSapHgQ",
		"CAACAgUAAxUAAWleQYAEOwdVyrvzfdb8b4mZ_q5-AAKRFgACDu65VLBg7C3pfEywHgQ",
		"CAACAgUAAxUAAWleQYAW88LJXYUEcXr4i3x_GaUbAALWFwACm8fBVPStjxQfclz1HgQ",
		"CAACAgUAAxUAAWleQYB7jSEniOCwhGoIJdmjKUm9AAIiFQACddIJVbsJzOgLoEQZHgQ",
	},
	"celebrate": {
		"CAACAgUAAxUAAWleQX8F06LYuWR35oVtGjVSroErAALiCwACTO94VFmn6s2oERiPHgQ",
		"CAACAgUAAxUAAWleQX9r5s54g_sh2VoBY1ikVP7cAAKoDwAC7ohAV7fcum0tXklxHgQ",
		"CAACAgUAAxUAAWleQX-BF1o37ify8qdwkwP6R5YxAALhEAACf-34V73oJrrcnezfHgQ",
		"CAACAgUAAxUAAWleQX-phRoh11RG9OBoR4xr07wtAALDGAACR7V5VKH-M_ztYAfuHgQ",
		"CAACAgUAAxUAAWleQYCLfAFX0WbpdMck9HI0gEuQAAIpDQACI_j5VqMQDy3VAAGOMx4E",
		"CAACAgUAAxUAAWleQYAFx_0N52-UbEZFLXxc7-yEAAKpEQAC6K_BVByrggSOP3W0HgQ",
		"CAACAgUAAxUAAWleQYCkjcDkbgkoBg7BiX61CqpnAAKWFQACa6MQVXsjbVbWBaCfHgQ",
	},
	"confused": {
		"CAACAgUAAxUAAWleQX_v40jM82xZ1MvSaICvgY3FAALxCQACyJEJVrecP9cyQUrvHgQ",
		"CAACAgUAAxUAAWleQX9kwaJgxLA1Yucnw-4kUEZRAAIdEAACmOCJV-jLdDxkjCLEHgQ",
		"CAACAgUAAxUAAWleQX8awFzAhDuSIyenxIdNJyxyAAKxGQACxdCZVJPFNZmHC146HgQ",
		"CAACAgUAAxUAAWleQYBix2cm8tE1wBP9nwUGghW1AAJoEgACNNXxVkVjSe66ZIypHgQ",
	},
	"cool": {
		"CAACAgUAAxUAAWleQX73EsE9mvzb5KzeK-zaA3A2AAKhDwACIhKpVcs0MrOcycfBHgQ",
		"CAACAgUAAxUAAWleQX_SZyRr1ELUDBt6ya3FsxikAAL9CgAChyYgVvq3kyZRLJz4HgQ",
		"CAACAgUAAxUAAWleQX_J_jV1M3mUwmh4ZGpVi7IPAALiDAACVNvQVj9gf-ArytGcHgQ",
		"CAACAgUAAxUAAWleQX_8vXOGmEo08L0HNl7KVvTrAAJOEQACRCagV03mnkARTDn4HgQ",
		"CAACAgUAAxUAAWleQX_KsudUBGt2Ur-IKhlSDyK8AAKGDwACeBTgVFGvncb51Q3ZHgQ",
		"CAACAgUAAxUAAWleQX9hqpFU7yHQrSrmwowJe5fxAAKEFgACFVCQVBdcmTAasEdhHgQ",
		"CAACAgUAAxUAAWleQYAEOwdVyrvzfdb8b4mZ_q5-AAKRFgACDu65VLBg7C3pfEywHgQ",
		"CAACAgUAAxUAAWleQYBQTWDLEnl2NIRUsuyUfqYbAAK-EwAC4pK5VJxyrXT6TUOWHgQ",
		"CAACAgUAAxUAAWleQYCvZkTY3wW28i501YxBl072AAK_FQACPC0RVeVmXDTDg27jHgQ",
	},
	"crying": {
		"CAACAgUAAxUAAWleQX9VFYhRwvFjqzECTXKWISHbAAKrCQAC7LQpVkrX2xTm4eKQHgQ",
		"CAACAgUAAxUAAWleQX8PuMVxmv1Y5ImLJgvZE_MkAALlEQACNQ15VYYhLapldtFiHgQ",
		"CAACAgUAAxUAAWleQX-E7Izuk6Jc_hC_eQwwSOMLAAKSDwAC1XngVgABgaKMIwM5GR4E",
		"CAACAgUAAxUAAWleQX_79g5LUv4olaR3h2hFldHGAALTFwAC3F7gVRZr1LNyaSpqHgQ",
		"CAACAgUAAxUAAWleQX-gYpczt5t5vtjDp9_KpZmDAAL5KgACUOqAVxOkmqSSBYoeHgQ",
		"CAACAgUAAxUAAWleQX_bJCI89x2L30ZQsFiRg-K8AAJpGAAC2-uJVDPR1Y-IdT7SHgQ",
		"CAACAgUAAxUAAWleQYALuIA4qQK6o3w6eA8N_BowAAL7DwACoCMJV3KiLj6miis1HgQ",
		"CAACAgUAAxUAAWleQYA8lZd1ubTTX5spA37X7wAB9wACaRAAAjpbyVcVU1wFkBh5vh4E",
		"CAACAgUAAxUAAWleQYCNXopvIl3MKlpYuktUrqzFAAIvEwAC9j_BVDwL3WCSeZDLHgQ",
		"CAACAgUAAxUAAWleQYCVMDLz2k0EEOLQjbuF-QfUAALlEgACpim4VKYqZEMJdTOyHgQ",
		"CAACAgUAAxUAAWleQYCkKijLNqquu1RWfN0TOu2rAAIRFQACrdy5VNj5w91v7LMcHgQ",
		"CAACAgUAAxUAAWleQYDzAVLaVWVdCcupg2PR0OoYAAIvGQACb6AJVWDIls3y1OXsHgQ",
	},
	"dismiss": {
		"CAACAgUAAxkBAAIHaGq31N5SCLd5wzEK9F1uN43J3bgJAAIzGgACC1zgVcX7DEwRHx80HgQ",
		"CAACAgUAAxkBAAIH-mq31N6EDZfuBCofMqIt-xQY7tJbAAL-GgACqtLgVfKGfKDIJ6AmHgQ",
	},
	"greeting": {
		"CAACAgUAAxUAAWleQYClnGcqptDlAi29_94vnosEAAJ7DgACn0cRV0HHMVIZOaaBHgQ",
	},
	"greeting_love": {
		"CAACAgUAAxUAAWleQYDxn0TcpE35P8REi9rp3NMnAALNDQACSm4JV8UN7-EeKr6QHgQ",
		"CAACAgUAAxUAAWleQYBzkRgwgPbwyNhjS0XLEpcQAALKFAACZpkIVeuEolwBeEgAAR4E",
	},
	"laughing": {
		"CAACAgUAAxUAAWleQX5u9-S9WKFBLBJRq4bXZt9fAAKXDQACETypVQUOy-Hk79i0HgQ",
		"CAACAgUAAxUAAWleQX9nNVcJOYufFnGkBSJqHDOQAAIcCwACBO8IVtJdWe0Um5czHgQ",
		"CAACAgUAAxUAAWleQX-Kez2IWTL8MjiwNJOgkvjjAAIPCQACzVgQVpFAwa7xA5f0HgQ",
		"CAACAgUAAxUAAWleQX-9kfzbnusuI9VqLNNv3jYTAALpCgACA8RwVK7Wg8ib_bTiHgQ",
		"CAACAgUAAxUAAWleQX9ji_bivaCPTfMXvqXJ4nZBAAIQDgACnx5pV3ebMCGEeSZpHgQ",
		"CAACAgUAAxUAAWleQX87NClkFxwt8RQ8Ml77nS1YAAKjFAACJogoVz41SuQ1EpI1HgQ",
		"CAACAgUAAxUAAWleQX-gYpczt5t5vtjDp9_KpZmDAAL5KgACUOqAVxOkmqSSBYoeHgQ",
		"CAACAgUAAxUAAWleQX8u-qXHFpH7L7e9nvlFe-NWAAJ-FwACauGBVBeenOoc6v-9HgQ",
		"CAACAgUAAxUAAWleQX_Tj9aQR66MCP1Pd-2QCnrZAAI9JAAC3USQVN4uHKW_DPRnHgQ",
		"CAACAgUAAxUAAWleQYCGVv7rH2TSggPxu2euekTpAAIuDwACeHzxVhKaNZXuoWHwHgQ",
		"CAACAgUAAxUAAWleQYCF6b6PxGKVMPN3GT8OY_mRAAJaDgACw8UZVytORfpJDjqWHgQ",
		"CAACAgUAAxUAAWleQYBGFK7X7AyUMziPDL4iy46FAAK_DgACXoFxVKHE1hdV8uFzHgQ",
		"CAACAgUAAxUAAWleQYAOkfIIKuVWHrL7i1RsS24-AAJWFwACT_PBVF3H8TrXdLyIHgQ",
		"CAACAgUAAxUAAWleQYD7dkhlcNnXIxDNnXjOXIpyAAIfFAACR6S5VGvV8aAwYKB3HgQ",
		"CAACAgUAAxUAAWleQYD7dkhlcNnXIxDNnXjOXIpyAAIfFAACR6S5VGvV8aAwYKB3HgQ",
		"CAACAgUAAxUAAWleQYD7dkhlcNnXIxDNnXjOXIpyAAIfFAACR6S5VGvV8aAwYKB3HgQ",
		"CAACAgUAAxUAAWleQYD7dkhlcNnXIxDNnXjOXIpyAAIfFAACR6S5VGvV8aAwYKB3HgQ",
		"CAACAgUAAxUAAWleQYD7dkhlcNnXIxDNnXjOXIpyAAIfFAACR6S5VGvV8aAwYKB3HgQ",
	},
	"love": {
		"CAACAgUAAxUAAWleQX5jnNFel8ytCn21_KvOyW_LAAL_DAACV9SpVTR0h7EtCD89HgQ",
		"CAACAgUAAxUAAWleQX75QV-2iHwz8977XWtuwiIxAAIPDgACpduoVUwVIfL25TOgHgQ",
		"CAACAgUAAxUAAWleQX-iu-FWmdDaOuiqMVQeuR9SAAJvGwACLex4VGfyYI9GdeTCHgQ",
		"CAACAgUAAxUAAWleQX_2UmVx-Cp3R0HFEFsFn7PNAAKMGAACHNaQVIOriyZB0KyKHgQ",
		"CAACAgUAAxUAAWleQX_2UmVx-Cp3R0HFEFsFn7PNAAKMGAACHNaQVIOriyZB0KyKHgQ",
		"CAACAgUAAxUAAWleQX_2UmVx-Cp3R0HFEFsFn7PNAAKMGAACHNaQVIOriyZB0KyKHgQ",
		"CAACAgUAAxUAAWleQX_2UmVx-Cp3R0HFEFsFn7PNAAKMGAACHNaQVIOriyZB0KyKHgQ",
		"CAACAgUAAxUAAWleQX_2UmVx-Cp3R0HFEFsFn7PNAAKMGAACHNaQVIOriyZB0KyKHgQ",
		"CAACAgUAAxUAAWleQX_2UmVx-Cp3R0HFEFsFn7PNAAKMGAACHNaQVIOriyZB0KyKHgQ",
		"CAACAgUAAxUAAWleQYDIov9pHOXNdL35t1mJNdQlAAJRDgACqswZVzoV8zZXmqRSHgQ",
		"CAACAgUAAxUAAWleQYCZy1Lo-cyYpbi-XDmSX_cyAAKjEAAC1XHIV0s35U-dT00wHgQ",
		"CAACAgUAAxUAAWleQYAEOwdVyrvzfdb8b4mZ_q5-AAKRFgACDu65VLBg7C3pfEywHgQ",
		"CAACAgUAAxUAAWleQYC3NMzbTxOAslM0B_NBnEFTAAI_FgAC3AcQVbVMSy30jXY3HgQ",
		"CAACAgUAAxUAAWleQYDTGfzYmGNSUBq0p3w64CsZAAIuFQACMbcJVa6GG1J0CAKDHgQ",
		"CAACAgUAAxkBAAIHf2q31N4wZwWptwnP2MDlzjXQUN32AALIFwACZEHgVdAoE7ZEudNNHgQ",
	},
	"neutral": {
		"CAACAgUAAxUAAWleQX72Tve-GvwOo_yomhHdImBlAAL2CwACoSepVZZpoYta8O-EHgQ",
		"CAACAgUAAxUAAWleQX5hiKXk1qHLZNjb57p7EY06AAKpDAACaQypVZAnNcab2r5THgQ",
		"CAACAgUAAxUAAWleQX-fn-bMs_vgbUMYRU7RfQABzwAClQsAAsouKVZ2LvzxIeoYSR4E",
		"CAACAgUAAxUAAWleQX-GiK86qJ872LJxUUs9V7DqAAIXCwACCWupVrxf8oecW03KHgQ",
		"CAACAgUAAxUAAWleQX-MtnphNjqWa2jwpYtcWzXEAAI-EQAC9e35Voxje_rt0Q1gHgQ",
		"CAACAgUAAxUAAWleQX8LYTaBl-6jQwGviJ13FN8MAAJzEwACo6f5VNWwhyYm18BEHgQ",
		"CAACAgUAAxUAAWleQX-bMpWBoCEI9LPiCuR71q00AAIvGQACzuKAVNW92IkjsZYzHgQ",
		"CAACAgUAAxUAAWleQYCmykf7caVb1-7zhGeK_oOeAAIZDwAC0CQZVxJUmB6KGdSNHgQ",
		"CAACAgUAAxUAAWleQYAOkfIIKuVWHrL7i1RsS24-AAJWFwACT_PBVF3H8TrXdLyIHgQ",
		"CAACAgUAAxUAAWleQYCesCLoUmQg6RVWDNoeLWx-AALsFwAC5J0QVaWX0ddLhVo5HgQ",
	},
	"playful": {
		"CAACAgUAAxkBAAIH7Wq31N6IGrtSdlhm-WGWCtqyUgoIAAJgJQAC8IXgVTSc9oMu8eqDHgQ",
		"CAACAgUAAxUAAWleQX5K-phZcfB6A9nrN_-Rp1pwAAJ1DQAClPLZV0DlvsH-04uiHgQ",
	},
	"sad": {
		"CAACAgUAAxUAAWleQX9b0CuADoD9-quGm04aqUuuAAIPDwACEL9pV2QsueOoJcAwHgQ",
		"CAACAgUAAxUAAWleQX9HfASgzXg4jwjjt0l-UqN4AALpDgACwPphV7W2B1axG5CMHgQ",
		"CAACAgUAAxUAAWleQX-g0B_mi2-uVSDBPZ919Oh3AAI2FQACWcV5VSd0LGEz0CixHgQ",
		"CAACAgUAAxUAAWleQX_iEEoxubZgjVgdKUQ3ZJY7AALsGQACcFiZVKkwT0OQsOghHgQ",
		"CAACAgUAAxUAAWleQYBoXEe9RiBVF9gIsBZliXs0AAJfEwACoNHwVtPVhCPUkDf3HgQ",
		"CAACAgUAAxUAAWleQYBvQ6KBKaRGz4BnVSJQ5YgoAAJoFgACCAnxVqjO5l7F6AqGHgQ",
		"CAACAgUAAxUAAWleQYCbrxUTRYonXY5PQmsmqpY3AALLFQACHni4VKMCW9GaebBvHgQ",
		"CAACAgUAAxUAAWleQYCkKijLNqquu1RWfN0TOu2rAAIRFQACrdy5VNj5w91v7LMcHgQ",
		"CAACAgUAAxUAAWleQYCkKijLNqquu1RWfN0TOu2rAAIRFQACrdy5VNj5w91v7LMcHgQ",
		"CAACAgUAAxUAAWleQYCkKijLNqquu1RWfN0TOu2rAAIRFQACrdy5VNj5w91v7LMcHgQ",
		"CAACAgUAAxUAAWleQYCkKijLNqquu1RWfN0TOu2rAAIRFQACrdy5VNj5w91v7LMcHgQ",
		"CAACAgUAAxUAAWleQYBJEINaxqeGGp5NkcZAERPDAAI2FQADxAlVxOF2wnL7-FgeBA",
	},
	"sassy": {
		"CAACAgUAAxUAAWleQX4U2Wezkr2trsOL30tnAdYUAAL7DAAC0vyoVUAG-buBMsPKHgQ",
		"CAACAgUAAxUAAWleQX9e5nHpNE830HSL1Lgfj2KcAALXEAACXVJhV-kDtLo7dTHiHgQ",
		"CAACAgUAAxUAAWleQX-6rNERxWTIUZflbJQoC0bpAAJEGgACUwqJVDlBCUVW7QE8HgQ",
		"CAACAgUAAxUAAWleQX9l7ShsvijYBrKBppVEDLTDAALHGQACgAqQVPsiRLTiObhZHgQ",
		"CAACAgUAAxUAAWleQX9r-NcP3Tz46DZ76HSfijsXAAKvGQACmvSQVIrUOLPg2scqHgQ",
		"CAACAgUAAxUAAWleQYA16l0PgVrOUVRGJwKEaW4lAALAEAAC6EfRV7WRstajugmMHgQ",
		"CAACAgUAAxUAAWleQYDAnWUbYCIHaHKiUwsITvYrAAK5EgACAbrBVFI1nsbDU5SDHgQ",
		"CAACAgUAAxUAAWleQYAEOwdVyrvzfdb8b4mZ_q5-AAKRFgACDu65VLBg7C3pfEywHgQ",
		"CAACAgUAAxUAAWleQYCFN0o5srIbIcOiz_bM-sSeAAIrEwACkKcIVX1pB0hf2eOVHgQ",
	},
	"secret": {
		"CAACAgUAAxkBAAIH72q31N5enGSZxwSUqW02XMOUu3QQAAKLHAACrnvhVZ-Pb5L49a72HgQ",
	},
	"shocked": {
		"CAACAgUAAxUAAWleQX9KQKHKsyBh3ec66HbziwS7AAI1DgACHIJBV9nWSHGXWWgVHgQ",
		"CAACAgUAAxUAAWleQX_MM34-1m3glFpdJavT4H9oAAJFFAACZpK4Vgwlnrv4YgouHgQ",
		"CAACAgUAAxUAAWleQX_kXgLXecIVipyk7nStji6ZAAK3EgAC9WPJVj8Hy5R-1tQjHgQ",
		"CAACAgUAAxUAAWleQX987joRgf0qd187JmEvVK4dAAKHHwACWTKQVCqAkWJILtvDHgQ",
		"CAACAgUAAxUAAWleQYCkKijLNqquu1RWfN0TOu2rAAIRFQACrdy5VNj5w91v7LMcHgQ",
	},
	"sleepy": {
		"CAACAgUAAxUAAWleQX_72vgLLqjINZqEOPq6-E88AALVDQACxFSxV4X7VWK8P0byHgQ",
		"CAACAgUAAxUAAWleQYAEOwdVyrvzfdb8b4mZ_q5-AAKRFgACDu65VLBg7C3pfEywHgQ",
	},
	"thinking": {
		"CAACAgUAAxUAAWleQX7NcU5HPVHhpsDHv4rG6uHCAAJLEAAC7hchVbMzEmnoGrI5HgQ",
		"CAACAgUAAxUAAWleQX_pwfct378dc7jalw98n67fAAIDFAACIUT4V3-HcxqN-HdZHgQ",
		"CAACAgUAAxUAAWleQX8ugFAm-Pwh9KlrokJXRgVUAAKVEAACUsHBVlULw6gFCRakHgQ",
		"CAACAgUAAxUAAWleQX95Vu378WADvpmlRozmLw6MAAIVDwACcNHJVkrItlpiLkpPHgQ",
		"CAACAgUAAxUAAWleQX8QlVhNW2F7EMVMGyhvYpDTAAKaFgAC_gmJVBO_VxG7Bm1SHgQ",
		"CAACAgUAAxUAAWleQYB90qmkAfjy9VwOyfZw7SdzAAL9DgAC8q0IV57RDhf4HJpuHgQ",
		"CAACAgUAAxUAAWleQYDcOHQNK3jyIat34TF6CdNKAALqEAACE5Y4VxeKg3IS1FAoHgQ",
		"CAACAgUAAxUAAWleQYA39-Akffdps1hmi3ucZmMwAAL3EgAC06i4VMNT0XFidS5QHgQ",
		"CAACAgUAAxUAAWleQYDhZI7Wa51dLHArDhRmS5NaAAJoFQACg5q4VLwzF5l38OhtHgQ",
		"CAACAgUAAxUAAWleQYBmRINyiJFfwUJrNqcnBXhzAALjEgACski4VKIsY6F37DKKHgQ",
	},
}

var rng = rand.New(rand.NewSource(time.Now().UnixNano()))

// GetStickerForCategory returns a random sticker file_id for the given category
func GetStickerForCategory(category string) string {
	if category == "" || category == "no_sticker" {
		return ""
	}
	stickers, exists := StickerCategories[category]
	if !exists || len(stickers) == 0 {
		return ""
	}
	return stickers[rng.Intn(len(stickers))]
}
